### PR TITLE
trace-ignore-plugin can also ignore LocalSpan and ExitSpan

### PR DESCRIPTION
**Pull request by xjs1919**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Sorry, this is not what sampling means in SkyWalking. Also, this causes half noop span included in trace, which also breaks a trace.

**Comment by xjs1919** [comment]
how can i ignore the local span and the exit span？

**Comment by wu-sheng** [comment]
You could remove relative plugin, or change source codes.
This is not just concept conflict, also cause unpredictable bugs.

**Comment by xjs1919** [comment]
”remove relative plugin" can not satisfy this kind of situation：
i want to see the detailed trace spans only when occurs an error in production environment，when there is no error，i just want to ignore these spans。 skywalking provides dynamic configurations， when combined with the dynamic configuration， i can resolve this situation。

**Comment by wu-sheng** [comment]
You can do what you feel right. You have source codes, don't need our permission.
The review is from upstream perspective, we are clear sampling focuses on segment, not span, very clearly.

**Pull request closed without merging**
