### PR TITLE
fix TracingSegmentRunner

### PR DESCRIPTION
**Pull request by JoeCqupt**
### Fix <bug description or the bug issue number or bug issue link>
- [ ] Add a unit test to verify that the fix works.
- [x] Explain briefly why the bug exists and how to fix it.
TracingSegmentRunner  override method withAfters made Junit @after annotation not work

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes https://github.com/apache/skywalking/issues/12210
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by lujiajing1126** [comment]
Nice catch. But you have to verify all test cases work as expected. I notice we've declared many `cleanup`s or `teardown`s. But they are actually not running at all.

**Comment by CodePrometheus** [comment]
I think `org.apache.skywalking.apm.agent.core.test.tools.TracingSegmentRunner#withAfters` also needs to be modified.

**Review by CodePrometheus — APPROVED** [review]
Now I think all cleanup and teardown could work correctly, the code LGTM, thanks @JoeCqupt for your attentive discovery and don't forget to update CHANGES, let's wait for other teachers to review.

**Comment by wu-sheng** [comment]
> Now I think all cleanup and teardown could work correctly, the code LGTM, thanks @JoeCqupt for your attentive discovery and don't forget to update CHANGES, let's wait for other teachers to review.

As no feature code change, no changelog required.

**Pull request merged**
