### PR TITLE
Polish up rabbitmq-5.x plugin to fix missing broker tag on consumer side

### PR DESCRIPTION
**Pull request by pg-yang**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

There is an issue about `NotNullAssertor` in agent  plugin test when checking tag with null value 

https://github.com/apache/skywalking-java/blob/6d5bbe8e5f7edec0cb10e3772266b6f632a04a34/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/util/TagValuePair.java#L41-L46
Like  above code , if the value of tag is null , we wouldn't set anything to value , and the value would be a blank string, , The   blank string is initiated by `KeyStringValuePair.Builder` which compiled by  protobuf . So the  result of  `NotNullAssertor` alway is true .

This is  `KeyStringValuePair.Builder` : 

image

This is  why the value of   tag `mq.broker`  is  null   ,but  the test sill passed 

https://github.com/apache/skywalking-java/blob/6d5bbe8e5f7edec0cb10e3772266b6f632a04a34/test/plugin/scenarios/rabbitmq-scenario/config/expectedData.yaml#L33

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
LGTM, wait for plugin tests to verify this doesn't break existing cases.

**Comment by pg-yang** [comment]
@wu-sheng  Did you look the above comment ?  
In a word  ,  `NotNullAssertor `  maybe not accurate  with tag which value is null .
We  could  provide  `NotBlankAssertor` in  test  tool project  , or  set the value to  keyValueBuilder even if it's null

**Comment by wu-sheng** [comment]
> We could provide NotBlankAssertor in test tool project , or set the value to keyValueBuilder even if it's null

Usually, we don't suggest post tag with empty value, so, we only have `not null` for now. If you feel necessary, `not blank` should be fine, but only for string field or tag.

**Comment by pg-yang** [comment]
Yes , I  think it's  necessary  , I previously confirmed  virtual mq related tag through   `expectedData.yaml` in  test case , and it  seems not accuracy for now  . 
Please wait until I finish `not blank` . It  could help us to check whether others mq plugin's  tag is right ?

**Comment by wu-sheng** [comment]
Make sense.

**Comment by pg-yang** [comment]
OK . Got  it

**Comment by wu-sheng** [comment]
So, I could merge this?

**Pull request merged**
