### PR TITLE
fix npe in guava eventbus plugin

### PR DESCRIPTION
**Pull request by xzyJavaX**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes https://github.com/apache/skywalking/issues/10967
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
I think we need to explain why the context could be either active or not?

**Comment by wu-sheng** [comment]
@xzyJavaX Any update?

**Comment by xzyJavaX** [comment]
When start a new thread to call `asyncEventBus.post(testEvent)`, the context will be inactive, this situation has no context.

**Comment by wu-sheng** [comment]
So, in this case, the posting message is not traced? Isn't this a bug rather than fix NPE?

**Comment by lujiajing1126** [comment]
> So, in this case, the posting message is not traced? Isn't this a bug rather than fix NPE?

It is traced but orphan. When calling `Context.continue` to correlate two Spans, it throws NPE since the TracingContext does not exist in a new thread.

I think it is users' responsibility to propagate tracing context in this case, e.g. use `@TraceCrossThread`.

This PR can only avoid NPE to be thrown.

**Comment by wu-sheng** [comment]
Make sense. Please fix the UT failing.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
