### PR TITLE
Add kylin jdbc plugin

### PR DESCRIPTION
**Pull request by xu1009**
### Add an agent plugin to support <framework name>
- [x] Add a test case for the new plugin, refer to [the doc](https://github.com/apache/skywalking-java/blob/main/docs/en/setup/service-agent/java-agent/Plugin-test.md)
- [x] Add a component id in [the component-libraries.yml](https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/resources/component-libraries.yml)
- [x] Add a logo in [the UI repo](https://github.com/apache/skywalking-rocketbot-ui/tree/master/src/views/components/topology/assets)

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<7869>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by xu1009** [comment]
image

image


image


image

**Comment by xu1009** [comment]
@wu-sheng there has code style xml for idea? i can format code in idea with the code style config xml

**Comment by xu1009** [comment]
image

local pass, this name is diff with the code?

**Comment by wu-sheng** [comment]
You forgot to change GitHub Action control file.

**Comment by xu1009** [comment]
> GitHub

== fix it

**Pull request merged**
