### PR TITLE
Optimize document and fix typo

### PR DESCRIPTION
**Pull request by Oliverwqcwrw**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
I noticed you closed the previous PR, what happens?

**Comment by Oliverwqcwrw** [comment]
After submitting the modification, I found that a check was not passed, but I did not know how to modify it, and then I close it

**Comment by Oliverwqcwrw** [comment]
It seems that the proto file has been modified, but I did not modify such files

**Comment by wu-sheng** [comment]
I can't see proto is modified by you.

**Comment by Oliverwqcwrw** [comment]
> Error: fatal: remote error: upload-pack: not our ref 17f05ee21d5bd3d40cfce5ccc8f0174316c47450
  Error: fatal: Fetched in submodule path 'apm-protocol/apm-network/src/main/proto', but it did not contain 17f05ee21d5bd3d40cfce5ccc8f0174316c47450. Direct fetching of that commit failed.
  fatal: 
  Error: The process '/usr/bin/git' failed with exit code 128

What's the problem

**Comment by wu-sheng** [comment]
This may be just a GHA random issue. We could rerun the task to verify.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
