### PR TITLE
Exclude synthetic methods for WitnessMethod

### PR DESCRIPTION
**Pull request by lujiajing1126**
### Fix https://github.com/apache/skywalking/issues/10679
- [x] Add a unit test to verify that the fix works.
- [x] Explain briefly why the bug exists and how to fix it.
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes https://github.com/apache/skywalking/issues/10679.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by lujiajing1126** [comment]
CI reported `grpc-core` 1.28.0 is not found @wu-sheng @kezhenxu94 any idea?

**Comment by wu-sheng** [comment]
The error is from Shenyi sofarpc case.

**Comment by lujiajing1126** [comment]
> The error is from Shenyi sofarpc case.

From CI logs,

image

Local build does not report any error

**Comment by wu-sheng** [comment]
@kezhenxu94 Any possible of cache issue?

**Comment by kezhenxu94** [comment]
I have deleted the cache and rerun the CI, let's see

**Comment by lujiajing1126** [comment]
> I have deleted the cache and rerun the CI, let's see

Seems not working

**Comment by wu-sheng** [comment]
I just excluded this case(`shenyu-2.4.x-sofarpc-scenario`), let's see.

**Comment by wu-sheng** [comment]
Other cases are passed. This is pretty strange.

**Review by wu-sheng — DISMISSED** [review]

**Comment by wu-sheng** [comment]
Friendly ping @yu199195 as PMC member of Shenyu in case of they know what happens.

**Comment by kezhenxu94** [comment]
> Local build does not report any error

@lujiajing1126 did you try removing the local jar of grpc-core 1.28.0?

**Comment by lujiajing1126** [comment]
> > Local build does not report any error
> 
> @lujiajing1126 did you try removing the local jar of grpc-core 1.28.0?

Yes. I've removed the whole io/grpc cache dir. But I have several maven mirrors. I am not sure which is used by GitHub CI?

**Comment by yu199195** [comment]
hi， io.grpc:grpc-core:jar:[1.28.0] can not find .

>  Failed to execute goal on project shenyu-sofarpc-gateway: Could not resolve dependencies for project org.apache.skywalking:shenyu-sofarpc-gateway:jar:1.0.0: Failed to collect dependencies at com.alipay.sofa:sofa-rpc-all:jar:5.7.6 -> io.grpc:grpc-netty-shaded:jar:1.28.0 -> io.grpc:grpc-core:jar:[1.28.0]: No versions available for io.grpc:grpc-core:jar:[1.28.0] within specified range -> [Help 1]

**Comment by kezhenxu94** [comment]
> > > Local build does not report any error
> > 
> > 
> > @lujiajing1126 did you try removing the local jar of grpc-core 1.28.0?
> 
> Yes. I've removed the whole io/grpc cache dir. But I have several maven mirrors. I am not sure which is used by GitHub CI?

GitHub CI doesn't use any mirror.

**Comment by wu-sheng** [comment]
> hi， io.grpc:grpc-core:jar:[1.28.0] can not find .
> 
> > Failed to execute goal on project shenyu-sofarpc-gateway: Could not resolve dependencies for project org.apache.skywalking:shenyu-sofarpc-gateway:jar:1.0.0: Failed to collect dependencies at com.alipay.sofa:sofa-rpc-all:jar:5.7.6 -> io.grpc:grpc-netty-shaded:jar:1.28.0 -> io.grpc:grpc-core:jar:[1.28.0]: No versions available for io.grpc:grpc-core:jar:[1.28.0] within specified range -> [Help 1]
> 
> > Failure to transfer io.grpc:grpc-core/maven-metadata.xml from https://mvnrepository.com/ was cached in the local repository, resolution will not be reattempted until the update interval of mvnrepository has elapsed or updates are forced. Original error: Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to mvnrepository (https://mvnrepository.com/): Authorization failed for https://mvnrepository.com/io/grpc/grpc-core/maven-metadata.xml 403 Forbidden

https://mvnrepository.com/artifact/io.grpc/grpc-core/1.28.0 still lists this version, which is very confused.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
