### PR TITLE
Add HikariCP connection pool plug-in.

### PR DESCRIPTION
**Pull request by VictorZeng**
### Add an agent plugin to support <framework name>
- [x] Add a test case for the new plugin, refer to [the doc](https://github.com/apache/skywalking-java/blob/main/docs/en/setup/service-agent/java-agent/Plugin-test.md)
- [x] Add a component id in [the component-libraries.yml](https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/resources/component-libraries.yml)
- [ ] Add a logo in [the UI repo](https://github.com/apache/skywalking-rocketbot-ui/tree/master/src/views/components/topology/assets)

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes https://github.com/apache/skywalking/issues/7753.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
General good to me.

**Comment by wu-sheng** [comment]
Please submit component definition to the main repository.

**Comment by VictorZeng** [comment]
> Please submit component definition to the main repository.

see https://github.com/apache/skywalking/pull/7755

**Comment by wu-sheng** [comment]
> > Please submit component definition to the main repository.
> 
> 
> 
> see https://github.com/apache/skywalking/pull/7755

Thanks. Wait for another reviewer.

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
