### PR TITLE
Bump up lombok version to 1.18.30 to support JDK21

### PR DESCRIPTION
**Pull request by OrezzerO**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

Fix compile problem when run scenario test.  

Lombok version smaller than 1.18.30 is not support JDK21. This pr bump up lombok version to 1.18.30 to support JDK21.

Related PR: [skywalking-agent-test-tool#57](https://github.com/apache/skywalking-agent-test-tool/pull/57)

### CODE REVIEW

**Comment by Superskyyy** [comment]
Eh, but how did the agent pass GitHub action testing though..?

**Comment by lujiajing1126** [comment]
> Fix compile problem when run scenario test.

I suppose you have to use JDK8 or 17 for those scenarios based on the workflows defined in the repo.

For other cases, the situation is unknown. Even if you've bumped up lombok version, other dependencies may not work.

**Comment by wu-sheng** [comment]
Agree, I have the same question, is this bump up necessary for all tests. Because basically, different tests are not expected to run on locked JDK versions. Some of the lib, especially old released versions, will never be able to run on JDK 21. Even if it can be, it is either transparent or relies on a new release.

**Comment by wu-sheng** [comment]
> Eh, but how did the agent pass GitHub action testing though..? or java agent hasn't been tested on jdk21 yet

The agent is ready, but the target libs may or may not, depending on the cases. 
This bump up is harmless, if you have to say. But this doesn't mean, all plugins can magically run on JDK 21 when the target libs can't by themselves.

**Comment by OrezzerO** [comment]
I follow the advice of [Java Agent Compiling porject](https://skywalking.apache.org/docs/skywalking-java/next/en/contribution/compiling/) and use JDK 21. I checked Github Action config,  even if  i use JDK 17, it is not all test case can run in  JDK 17, most cases are in JDK1.8 environment.  There is a little problem between documents and actual situation. 

Back to this pr, is there some others i need to do?

**Comment by lujiajing1126** [comment]
> I follow the advice of [Java Agent Compiling porject](https://skywalking.apache.org/docs/skywalking-java/next/en/contribution/compiling/) and use JDK 21. There is a little problem between documents and actual situation.

The doc does not say anything about E2E. You **MUST** follow the steps in the workflow to run all E2E cases.

> I checked Github Action config, even if i use JDK 17, it is not all test case can run in JDK 17, most cases are in JDK1.8 environment.

Exactly

**Comment by wu-sheng** [comment]
Close for now

**Pull request closed without merging**
