### PR TITLE
Record the time the request was submitted to the tomcat thread pool to the request header

### PR DESCRIPTION
**Pull request by zanpocc**
### Add an agent plugin to support record the time the request was submitted to the tomcat thread pool to the request header

- [ ] Add a test case for the new plugin
- [ ] Add a component id 
- [ ] Add a logo

Can I merge into this repository？ 😳

### CODE REVIEW

**Comment by wu-sheng** [comment]
I can't see why you add this random thing to SkyWalking Java agent.
This doesn't follow any existing fields.

**Comment by zanpocc** [comment]
> I can't see why you add this random thing to SkyWalking Java agent. This doesn't follow any existing fields.

I think this helps to monitor the time it takes for a request to be submitted to the thread pool by tomcat poll until it is executed. why is random thing

**Comment by wu-sheng** [comment]
SkyWalking scope is very clear. And our APIs provide key features and protocols define the boundaries.
We would not inject random things to user applications.

Notice, I am not saying you are wrong, my point is, this could be your private plugin, or your own open source project in you repo.

The offical plugins only host defined scope things. Yours are not in that scope.

**Comment by zanpocc** [comment]
> SkyWalking scope is very clear. And our APIs provide key features and protocols define the boundaries. We would not inject random things to user applications.
> 
> Notice, I am not saying you are wrong, my point is, this could be your private plugin, or your own open source project in you repo.
> 
> The offical plugins only host defined scope things. Yours are not in that scope.

i get it.
maybe I should write something more general to integrate with skywalking.
I just don't see anything like that in skywalking.

**Comment by zanpocc** [comment]
i will close this pull

**Comment by Superskyyy** [comment]
Maybe next time please first open an discussion in the main repo to talk about it before opening pull requests. Then it will have higher chance of getting merged.

**Comment by zanpocc** [comment]
> @zanpocc Maybe next time please first open a discussion in the main repo to talk about it before opening pull requests. Then it will have a higher chance of getting merged.

ok，I thought it was maintained separately

**Comment by wu-sheng** [comment]
>maybe I should write something more general to integrate with skywalking.

This is a strange perspective. Are you purely trying to contribute some features? If not, a private use for your own case is totally fine. That is normal in open source.

**Pull request closed without merging**
