### PR TITLE
Transport maybe is not a EnhancedInstance.

### PR DESCRIPTION
**Pull request by xiaolongzuo**
### Fix <Transport maybe is not a EnhancedInstance. For example, a TFrameTransport encapsulating TSocket.>
- [ ] Add a unit test to verify that the fix works.
- [x] Explain briefly why the bug exists and how to fix it.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
You should use `instanceof` rather than a `catch`.

**Comment by wu-sheng** [comment]
> Fix <Transport maybe is not a EnhancedInstance. For example, a TFrameTransport encapsulating TSocket.>

So, in `TFrameTransport` case, `UNKNOWN` is good enough?

**Comment by wu-sheng** [comment]
Are you going to explain what you are proposing to change?

**Comment by wu-sheng** [comment]
This PR has no update in half month. I have to close this.
If you want to continue on this, let's know.

**Comment by xiaolongzuo** [comment]
> > Fix <Transport maybe is not a EnhancedInstance. For example, a TFrameTransport encapsulating TSocket.>
> 
> So, in `TFrameTransport` case, `UNKNOWN` is good enough?

The best way is to enumerate all the situations and take out the correct peers for these situations. However, I'm not sure of any other situations. TFrameTransport is just one of the ones I encounter in my own use.

**Comment by wu-sheng** [comment]
If you still want to finish this PR, please follow the comments of the review.

About the UNKNOWN, I just want to make sure which field is going to be set as UNKNOW and how it looks like on the UI?

**Comment by xiaolongzuo** [comment]
> If you still want to finish this PR, please follow the comments of the review.

1、Which field is going to be set as UNKNOW？ 
A：Peer of exit span, likes below.
image
2、How it looks like on the UI?
A：I think it should be UNKNOWN in the peer, but I haven't tested this.

**Comment by wu-sheng** [comment]
Peer as UNKNOWN? Then the node of topology would be unknown, this seems not right.

As on the client side, you should be able to get remote service logic name, or IP/DNS address, right?

**Pull request closed without merging**
