### PR TITLE
Fix H2 instrumentation point

### PR DESCRIPTION
**Pull request by 2han9wen71an**
- [x]  `org.apache.skywalking.apm.plugin.jdbc.jdbc.JdbcXAConnectionConstructorInterceptor` doesn't exist, the one should be  `org.apache.skywalking.apm.plugin.jdbc.h2.JdbcXAConnectionConstructorInterceptor`

### CODE REVIEW

**Comment by wu-sheng** [comment]
We only accept English description. Could you update them? And changelog should be updated as well.

**Comment by wu-sheng** [comment]
@pg-yang Could you check on this?

**Comment by 2han9wen71an** [comment]
> We only accept English description. Could you update them? And changelog should be updated as well.

english description updated

**Comment by wu-sheng** [comment]
There is a changes.md in the root. Please update as well.

**Comment by wu-sheng** [comment]
@2han9wen71an Once changes updated, this PR should be good.

**Review by pg-yang — APPROVED** [review]
LGTM, thanks

**Comment by 2han9wen71an** [comment]
> @2han9wen71an一旦更改更新，这个 PR 应该是好的。



> @2han9wen71an Once changes updated, this PR should be good.

Updated, I've recently been fixing skywalking not working under osgi environment, and it has been verified successfully under polarion so far. Looking forward to our next meeting!

**Comment by wu-sheng** [comment]
That is better. Before you propose changes, please submit a discuss to explain why it didn't work and what is your solution.

**Pull request merged**
