### PR TITLE
Optimizing the type pool of byte-buddy (#11460)

### PR DESCRIPTION
**Pull request by kylixs**
### Improve the performance of type pool of byte-buddy
Add type pool cache to byte-buddy
Problem discussion here: https://github.com/apache/skywalking/issues/11460

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #11460
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by lujiajing1126** [comment]
Thanks for the patch. But actually it seems no change for the startup time.

**Comment by wu-sheng** [comment]
I can see the diff is hybrid doesn't support loaded classes. I think that is for attach agent?

**Comment by wu-sheng** [comment]
I verified here, https://github.com/apache/skywalking-java/pull/635, and [retransform-class-tomcat-scenario](https://github.com/apache/skywalking-java/actions/runs/6665572476/job/18115743332?pr=635#logs) failed 3 minutes ago in 1m 26s, but other cases are passed. 

@kylixs How about we add a configuration to disable this as retransfer is not that popular. And we could unify them if we could find a better solution.

And we could update the configuration doc and FAQ to highlight this.

**Comment by wu-sheng** [comment]
I opened https://github.com/apache/skywalking-java/pull/636 to make this configurable. 

@kylixs If you have a solution for this, welcome to override my change.

**Pull request closed without merging**
