### PR TITLE
Add thrift plugin support thrift TMultiplexedProcessor.

### PR DESCRIPTION
**Pull request by zifeihan**
### Fix thrift plugin does not support thrift TMultiplexedProcessor, so NPE is triggered
- [ ] Add a unit test to verify that the fix works.
   It has been tested through the demo submitted by the user. I have been too busy recently. I will submit the test scenario in two days.
- [x] Explain briefly why the bug exists and how to fix it.
   Check [7571]( https://github.com/apache/skywalking/issues/7571) to understand the cause of the bug and how to fix it.

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #7571 .
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by dmsolr** [comment]
I think this is an enhancement. :)
We don't implement all `Processor`s.

**Comment by dmsolr** [comment]
Hi @lzdujing Please check it if you have time.

**Comment by dmsolr** [comment]
@zifeihan maybe we need to list of `Processor`s in docs which we have enhanced, WDYT?

**Comment by zifeihan** [comment]
> @zifeihan maybe we need to list of `Processor`s in docs which we have enhanced, WDYT?

Ihink it is necessary. Currently thrift only has 3 processors, and we currently support all of them.

**Comment by dmsolr** [comment]
> > @zifeihan maybe we need to list of `Processor`s in docs which we have enhanced, WDYT?
> 
> I think it is necessary. Currently thrift only has 3 processors, and we currently support all of them.

Actually, not only these are 3. There are also many wrapped processors.

**Comment by zifeihan** [comment]
image
The object here is new, so it does not go through ServerInProtocolWrapper, so special judgment is required

**Review by dmsolr — APPROVED** [review]
LGTM, @zifeihan told me who is too busy to complete docs.

**Comment by wu-sheng** [comment]
> LGTM, @zifeihan told me who is too busy to complete docs.

Hi, we don't have typically documents to host all logic of plugins, they are too complex to describe. AFAIK, only very few plugin added README.md in the root of plugin source codes only. @dmsolr If you want to, welcome to send a pull request later.

**Pull request merged**
