### PR TITLE
[ISSUE #9264] fix onHalfClose span operation name

### PR DESCRIPTION
**Pull request by drgnchan**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes https://github.com/apache/skywalking/issues/9264
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please update changes.md in the root.

**Comment by wu-sheng** [comment]
I think you forgot to change gRPC relative tests? The plugin tests fail.

**Comment by drgnchan** [comment]
> I think you forgot to change gRPC relative tests? The plugin tests fail.

Yes.I think i know how to fix it.I am sorry that i cannot fix it right now without a pc.I will start to fix it in 2 hours later.

**Comment by wu-sheng** [comment]
Don't hurry. Fix it when you have time.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
