### PR TITLE
Update support-version.list for Pulsar test scenario

### PR DESCRIPTION
**Pull request by codelipenghui**
- Replace 2.7.0 with 2.7.3

### CODE REVIEW

**Review by kezhenxu94 — DISMISSED** [review]
LGTM once tests passed

**Comment by codelipenghui** [comment]
Sorry, looks like 2.7.3 have not synced to maven central yet, will update after the package is available in maven central.

**Comment by wu-sheng** [comment]
> Sorry, looks like 2.7.3 have not synced to maven central yet, will update after the package is available in maven central.

Is the release process done?

**Comment by codelipenghui** [comment]
@wu-sheng Yes, released but waiting for sync to the maven central.

**Comment by wu-sheng** [comment]
> @wu-sheng Yes, released but waiting for sync to the maven central.

Usually this sync doesn't need so long time, please check whether release manager has clicked the `release` from ASF nexus to maven central

**Comment by codelipenghui** [comment]
@kezhenxu94 @wu-sheng I have removed 2.8.1 due to there are some change makes the plugins does not compatible with 2.8 anymore, I will follow the 2.8.x compatibility issue. For the 2.7.3, it is available in Maven Central for now

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
