### PR TITLE
Fix a thread leak in `SamplingService` when updated sampling policy in the runtime.

### PR DESCRIPTION
**Pull request by hyhyf**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by hyhyf** [comment]
[https://github.com/apache/skywalking/discussions/10549#discussioncomment-5437985](url)

**Comment by wu-sheng** [comment]
Which JDK are you using? Have you checked the source codes?

**Comment by wu-sheng** [comment]
I think the change makes sense. It is a leak. `scheduledFuture#cancel` doesn't close the whole pool actually.

**Comment by wu-sheng** [comment]
@hyhyf Please add `* Fix a thread leak in `SamplingService` when updated sampling policy in the runtime.` as the change log into the `changes.md` in the root. We need the description for the changes.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
