### PR TITLE
Support tencent sms

### PR DESCRIPTION
**Pull request by houxinlin**
1. Support tencent sms

### CODE REVIEW

**Comment by wu-sheng** [comment]
Hi, first of all, thanks for your consideration of the contribution.
But I am afraid that, we can't accept this. 
We don't have change to verify this plugin especially in CI process, which is required by all plugins. 
Meanwhile, we don't have a single one committer from Tencent cloud, which means no committer could verify this.

It may be better you could host and release on your own repository.

**Comment by houxinlin** [comment]
> Hi, first of all, thanks for your consideration of the contribution. But I am afraid that, we can't accept this. We don't have change to verify this plugin especially in CI process, which is required by all plugins. Meanwhile, we don't have a single one committer from Tencent cloud, which means no committer could verify this.
> 
> It may be better you could host and release on your own repository.

Okay, I understand. Thank you

**Comment by Superskyyy** [comment]
> > Hi, first of all, thanks for your consideration of the contribution. But I am afraid that, we can't accept this. We don't have change to verify this plugin especially in CI process, which is required by all plugins. Meanwhile, we don't have a single one committer from Tencent cloud, which means no committer could verify this.
> 
> > 
> 
> > It may be better you could host and release on your own repository.
> 
> 
> 
> I would like to contribute a skywalking API to provide a query interface. Does the community need it?

Could you elaborate on what it does? I see you have a repo for that but there isn't code yet.

**Comment by houxinlin** [comment]
> Isn't GraphQL designed for this? Are you suggesting a kind of Java SDK?

I'm sorry to initiate a discussion at this time and disturb your rest

> Isn't GraphQL designed for this? Are you suggesting a kind of Java SDK?

I'm sorry to initiate a discussion at this time and disturb your rest,

**Comment by wu-sheng** [comment]
> > Isn't GraphQL designed for this? Are you suggesting a kind of Java SDK?
> 
> 
> 
> Yes, sometimes we need to continue querying data directly from the database when skywalking is not started or there are exceptions

Please open a discussion about your new proposal.

**Comment by houxinlin** [comment]
> > > Isn't GraphQL designed for this? Are you suggesting a kind of Java SDK?
> > 
> > 
> > Yes, sometimes we need to continue querying data directly from the database when skywalking is not started or there are exceptions
> 
> Please open a discussion about your new proposal.

ok

**Pull request closed without merging**
