### PR TITLE
support jersey rest framework

### PR DESCRIPTION
**Pull request by xu1009**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. https://github.com/apache/skywalking/issues/10739
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why close and open a new one?

**Comment by xu1009** [comment]
i find lost some code==

**Comment by xu1009** [comment]
scenario test project does not import checkstyle plugin，it can compile success local，i need import checkstyle plugin myself，and remove it before ci

**Comment by wu-sheng** [comment]
That is done through script.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
