### PR TITLE
Add tomcat 10 plugin

### PR DESCRIPTION
**Pull request by wutingjia**
### Add an agent plugin to support <tomcat-10.x-plugin>
- [x] Add a test case for the new plugin, refer to [the doc](https://github.com/apache/skywalking-java/blob/main/docs/en/setup/service-agent/java-agent/Plugin-test.md)
- [ ] Add a component id in [the component-libraries.yml](https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/resources/component-libraries.yml)
- [ ] Add a logo in [the UI repo](https://github.com/apache/skywalking-rocketbot-ui/tree/master/src/views/components/topology/assets)
     

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes https://github.com/apache/skywalking/issues/7420.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Have you passed the test locally?

**Comment by wu-sheng** [comment]
Where do you build the test service running in the Tomcat 10 container? Could you make this clear?

**Comment by wutingjia** [comment]
Unfortunately，I just passed the unit test，the test framework is still failed locally，I would like to know if I am allowed to test online with GHA or CI process or some others. If not，I may spend some time to build a linux subsystem and try again

**Comment by wu-sheng** [comment]
You can run GHA on your own GitHub repository, but should not be on upstream.

Change the GHA YAML file, run in any repo you like. Also, in my mind, a Linux server is easy to find, and have better performance.

**Comment by wutingjia** [comment]
> You can run GHA on your own GitHub repository, but should not be on upstream.
> 
> Change the GHA YAML file, run in any repo you like. Also, in my mind, a Linux server is easy to find, and have better performance.
ok，thanks for instruction~

**Pull request closed without merging**
