### PR TITLE
Expose  config to set up the re-transform support explicitly

### PR DESCRIPTION
**Pull request by wu-sheng**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes https://github.com/apache/skywalking/issues/11460
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

I am waiting for @lujiajing1126 final report about this case in their environment.

### CODE REVIEW

**Comment by lujiajing1126** [comment]
For a real workload with ~30 classes to be enhanced. 

## Local env

- OS: macOS sonoma 14.0
- JDK: 1.8.0_372
- Hardware spec: Apple M2 with 16GB memory

| Variant | premain exec time* |
|----|----|
| POOL_FIRST  | ~6 secs |
| HYBRID |  |

* specifically `agentBuilder.installOn(instrumentation)`

**Comment by wu-sheng** [comment]
@lujiajing1126 I updated the doc, please take a look.

**Review by lujiajing1126 — APPROVED** [review]
LGTM

**Comment by kylixs** [comment]
This option might be better changed to enable or disable custom byte-buddy patch, for compatibility reasons.

**Comment by wu-sheng** [comment]
Compatible with which part? 
I am waiting for your PR feedback. If it is good enough, we don't need this.

**Comment by kylixs** [comment]
Determine whether to use a custom `AgentBuilder` with patch or a normal one: 
```java
    private static AgentBuilder newAgentBuilder(SWDescriptionStrategy descriptionStrategy) {
        final ByteBuddy byteBuddy = new ByteBuddy()
                .with(TypeValidation.of(Config.Agent.IS_OPEN_DEBUGGING_CLASS))
                .with(new SWAuxiliaryTypeNamingStrategy(NAME_TRAIT))
                .with(new SWImplementationContextFactory(NAME_TRAIT));

        return new SWAgentBuilderDefault(byteBuddy, new SWNativeMethodStrategy(NAME_TRAIT))
                .with(descriptionStrategy);
    }
```

**Comment by wu-sheng** [comment]
I don't think we need to expose. This should not be aware ny users.
Anyone doesn't read codes, don't know what this is about.

**Comment by kylixs** [comment]
I mean the option is `SW_ENABLE_RETRANSFORM_SUPPORT`,  disable byte-buddy patch if it is false. Users can understand this option.

**Comment by wu-sheng** [comment]
I know your point. But I doubt they will know what path or our customization mean.

**Comment by wu-sheng** [comment]
Like I documented, it should be a straight forward. If there are really some issues of your patch, that is a bug, nothing more

**Comment by kylixs** [comment]
I agree. I'm just wondering if there's a fallback mechanism that can be enabled if something goes wrong.

**Comment by wu-sheng** [comment]
Close for now, as we seems to have a solution now.

**Pull request closed without merging**
