### PR TITLE
string "/eureka" should match pattern "/eureka/*" or "/eureka/**" 

### PR DESCRIPTION
**Pull request by xjs1919**

### CODE REVIEW

**Comment by devkanro** [comment]
After my test, AntPathMatcher do not match this rule.

```Kotlin
AntPathMatcherAntPathMatcher().match("/eruka/*", "/eruka") // false
```

**Comment by wu-sheng** [comment]
If this does follow ant path match, I have concerns about this, whether this us reasonable.

**Comment by devkanro** [comment]
> If this does follow ant path match, I have concerns about this, whether this is reasonable.

@wu-sheng `/eureka/**` matches `/eureka`, but `/eureka/*` not.

**Comment by wu-sheng** [comment]
OK, got your point. Both should support.

**Comment by wu-sheng** [comment]
I just want to ask, whether 2 configs make more sense than supporting this kind of config? After all, /* means at least having a /.

My concern is about this.

**Comment by wu-sheng** [comment]
Is there other tools supporting in this way?

**Comment by devkanro** [comment]
@wu-sheng 
No, I means the current behavior of AntPathMatcher is `/eureka/**` matches `/eureka`, but `/eureka/*` not.

**Comment by devkanro** [comment]
I am don't sure my FastPathMatcher's behavior, I will get test for it.

**Comment by devkanro** [comment]
There are my test result, use 'AntPathMatcher/FastPathMatcher'

```Kotlin
matches("/eureka/*", "/eureka") = false/false
matches("/eureka/*", "/eureka/") = true/true
matches("/eureka/*", "/eureka/test/") = false/true
matches("/eureka/*", "/eureka/test") = true/true
matches("/eureka/*/", "/eureka") = false/false
matches("/eureka/*/", "/eureka/") = true/false
matches("/eureka/*/", "/eureka/test") = false/false
matches("/eureka/*/", "/eureka/test/") = true/true
matches("/eureka/**", "/eureka") = true/false
matches("/eureka/**", "/eureka/") = true/true
matches("/eureka/**", "/eureka/test/") = true/true
matches("/eureka/**", "/eureka/test") = true/true
matches("/eureka/**/", "/eureka") = true/false
matches("/eureka/**/", "/eureka/") = true/true
matches("/eureka/**/", "/eureka/test") = true/true
matches("/eureka/**/", "/eureka/test/") = true/true
```

**Comment by devkanro** [comment]
Highlights for diff

```
matches("/eureka/*", "/eureka/test/") = false/true
matches("/eureka/*/", "/eureka/") = true/false
matches("/eureka/**", "/eureka") = true/false
matches("/eureka/**/", "/eureka") = true/false
```

**Comment by wu-sheng** [comment]
Are these diff from previous or PR version?

**Comment by devkanro** [comment]
The diff is about Spring's AntPathMatcher between my FastPathMatcher in current production version of skywalking.

I am not compare the PR version.

**Comment by devkanro** [comment]
By comparison, FastPathMatcher seems more intuitive?

Case 1:
`/eureka/*` vs `/eureka/test/`
* means zero or one path part, but a path part may have ends with / or not.

Case 2:
`/eureka/*/` vs `/eureka/`
* means zero or one path part, but if it means zero, the path should be `/eureka//`, can we omit the double /?

Case 3:
`/eureka/**` vs `/eureka`
/** means at least one /

Case 4:
`/eureka/**/` vs `/eureka`
**/ means path should ends with /

**Comment by wu-sheng** [comment]
I feel like the current version is good. I am not sure why Spring works in a different way.

**Comment by devkanro** [comment]
Spring's AntPathMatcher is copy from Apache Ant.

**Comment by wu-sheng** [comment]
@xjs1919 Please update with us, why do you think this behavior makes sense?

**Comment by xjs1919** [comment]
> @xjs1919 Please update with us, why do you think this behavior makes sense?

i want to ignore path contains "actuator", so i have to config like this :

trace.ignore_path=${SW_AGENT_TRACE_IGNORE_PATH:**/actuator/**,GET:/actuator}

it works, however a little redundant and not graceful，and Spring's AntPathMatcher can match "/eureka" with pattern "/eureka/**"

**Comment by wu-sheng** [comment]
I am not sure why AntPathMatcher works like that, but to be honest, I don't think it is the standard. 
`/eureka/**` ignoring `/eureka` seems unreasonable. Maybe Spring team has their reasons, but logically, this is right.

**Comment by wu-sheng** [comment]
Closing due to support @devkanro 's opinion(original author)

**Pull request closed without merging**
