### PR TITLE
Upgrade Kafka clients dependency version to 3.8.0

### PR DESCRIPTION
**Pull request by Super-Lu**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes https://github.com/apache/skywalking/issues/12800.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
As discussed, I don't think updating this works. Have you tested with a Kafka cluster and OAP?

**Comment by Super-Lu** [comment]
> As discussed, I don't think updating this works. Have you tested with a Kafka cluster and OAP?

Yes, I have already tested the Kafka client version 3.8.0 locally to connect to the Kafka cluster and report link data to OAP. Currently, the data reporting to OAP is normal.

**Comment by wu-sheng** [comment]
Let's see how the e2e says.

**Comment by wu-sheng** [comment]
If all are working, remember to update the change log accordingly.

**Comment by wu-sheng** [comment]
image

The e2e reports failure. Please recheck this e2e.

**Comment by wu-sheng** [comment]
Maybe because of Kafka server version? Or something?

**Comment by Super-Lu** [comment]
> Maybe because of Kafka server version? Or something?



> image
> The e2e reports failure. Please recheck this e2e.
Okay, I'll check it out.

**Comment by lujiajing1126** [comment]
Starting from Kafka Clients 3.0, acks
 is changed from 1 to all, and idempotent is enabled by default.

It will lead to increasing latency. I suppose it is not necessary for telemetry cases.

**Comment by lujiajing1126** [comment]
> Maybe we could change that configuration? Can we?
> 
> Personally, the issue is we can't stay in an old and not-releasing version, as suffering CVEs.

I think we can keep the current configurations by setting default properites

**Comment by Super-Lu** [comment]
> > Maybe we could change that configuration? Can we?
> > Personally, the issue is we can't stay in an old and not-releasing version, as suffering CVEs.
> 
> I think we can keep the current configurations by setting default properites

 Could you please tell me what modifications I need to make in order to pass the test cases, and then I can merge my code into the main repository?

**Comment by wu-sheng** [comment]
Any update? we should make the tests passed, then we talk about default configurations.

**Comment by Super-Lu** [comment]
> Any update? we should make the tests passed, then we talk about default configurations.

Sorry to bother you, I need some help. How can I run test cases locally? Are there any guide documents available?

**Comment by wu-sheng** [comment]
Which part? e2e? You could follow this, https://skywalking.apache.org/docs/skywalking-infra-e2e/latest/en/setup/run-e2e-tests/

**Comment by Super-Lu** [comment]
> Which part? e2e? You could follow this, https://skywalking.apache.org/docs/skywalking-infra-e2e/latest/en/setup/run-e2e-tests/

Thanks, this is the guide document I needed.

**Pull request closed without merging**
