### PR TITLE
Optimize service conflict error message

### PR DESCRIPTION
**Pull request by wongtp**
### Optimize service conflict error message
see like [intercept failure](https://github.com/apache/skywalking/issues/10991), sometimes the service conflict will print the error message to the skywalking-api.log, but not enough to find which service conflict.

before optimize
```
INFO 2024-01-18 13:41:21.946 main SkyWalkingAgent : Skywalking agent transformer has installed. 
ERROR 2024-01-18 13:41:22.270 main SkyWalkingAgent : Skywalking agent boot failure. 
org.apache.skywalking.apm.agent.core.boot.ServiceConflictException: Service class org.apache.skywalking.apm.plugin.cpu.policy.TraceSamplerCpuPolicyExtendService overrides conflict, exist more than one service want to override :class org.apache.skywalking.apm.agent.core.sampling.SamplingService
	at org.apache.skywalking.apm.agent.core.boot.ServiceManager.loadAllServices(ServiceManager.java:89)
	at org.apache.skywalking.apm.agent.core.boot.ServiceManager.boot(ServiceManager.java:42)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
```

after optimize
```
INFO 2024-01-18 22:21:14.458 main SkyWalkingAgent : Skywalking agent transformer has installed. 
ERROR 2024-01-18 22:21:14.754 main SkyWalkingAgent : Skywalking agent boot failure. 
org.apache.skywalking.apm.agent.core.boot.ServiceConflictException: Service class org.apache.skywalking.apm.plugin.cpu.policy.TraceSamplerCpuPolicyExtendService overrides conflict, more then one service found, service[class org.apache.skywalking.apm.agent.core.sampling.SamplingService] want to override[class org.apache.skywalking.apm.plugin.trace.ignore.TraceIgnoreExtendService], please check your plugins
	at org.apache.skywalking.apm.agent.core.boot.ServiceManager.loadAllServices(ServiceManager.java:92)
	at org.apache.skywalking.apm.agent.core.boot.ServiceManager.boot(ServiceManager.java:42)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
```

### CODE REVIEW

**Comment by lujiajing1126** [comment]
I am confused why this is related to the https://github.com/apache/skywalking/issues/10991?

The linked issue may be caused by version compatibility of the Netty plugin. It must not relevant to the kernel.

**Comment by wongtp** [comment]
> I am confused why this is related to the [apache/skywalking#10991](https://github.com/apache/skywalking/issues/10991)?
> 
> The linked issue may be caused by version compatibility of the Netty plugin. It must not relevant to the kernel.

@lujiajing1126 Because of while plugins conflict, the `ServiceManager.bootedServices` will not initial, then all intercept failure.

image
WXWorkCapture_17056561825966

**Comment by wu-sheng** [comment]
@wongtp The argument is, that the reason of the changes is not clear. If you just want to enhance logs to make the conflicts more readable, I think it is OK to accept.
But the issue you are referring to, it is not clearly related to this change.

We need to keep the discussion context clear.

**Comment by wongtp** [comment]
> I am confused why this is related to the [apache/skywalking#10991](https://github.com/apache/skywalking/issues/10991)?
> 
> The linked issue may be caused by version compatibility of the Netty plugin. It must not relevant to the kernel.

I checked again the relate issue [intercept failure](https://github.com/apache/skywalking/issues/10991), It should be relate to [issues/11205](https://github.com/apache/skywalking/issues/11205)

**Comment by wu-sheng** [comment]
@lujiajing1126 Could you recheck the new linked issue?

**Comment by lujiajing1126** [comment]
> > I am confused why this is related to the [apache/skywalking#10991](https://github.com/apache/skywalking/issues/10991)?
> > The linked issue may be caused by version compatibility of the Netty plugin. It must not relevant to the kernel.
> 
> @wu-sheng @lujiajing1126 I am so sorry, this was my mistake, I checked again the relate issue [intercept failure](https://github.com/apache/skywalking/issues/10991), it should be relate to [issues/11205](https://github.com/apache/skywalking/issues/11205), when `ServiceManager.bootedServices` initial failure, it will print many of NPE error message in skywalking-api.log, I hope this optimeize can help us to find the cause of the problem quickly.

As I comment here, https://github.com/apache/skywalking/issues/11205#issuecomment-1902871724 is caused by misunderstanding of the webflux scenario.

I am going to close the issue since it actually resolve neither of the issues the author linked here.

Feel free to reopen this if you have further idea.

**Comment by wongtp** [comment]
> > > I am confused why this is related to the [apache/skywalking#10991](https://github.com/apache/skywalking/issues/10991)?
> > > The linked issue may be caused by version compatibility of the Netty plugin. It must not relevant to the kernel.
> > 
> > 
> > @wu-sheng @lujiajing1126 I am so sorry, this was my mistake, I checked again the relate issue [intercept failure](https://github.com/apache/skywalking/issues/10991), it should be relate to [issues/11205](https://github.com/apache/skywalking/issues/11205), when `ServiceManager.bootedServices` initial failure, it will print many of NPE error message in skywalking-api.log, I hope this optimeize can help us to find the cause of the problem quickly.
> 
> As I comment here, [apache/skywalking#11205 (comment)](https://github.com/apache/skywalking/issues/11205#issuecomment-1902871724) is caused by misunderstanding of the webflux scenario.
> 
> I am going to close the issue since it actually resolves neither of the issues the author linked here.
> 
> Feel free to reopen this if you have further idea.

@lujiajing1126 You are right, it can't resolve that problem and don't have much to do with each other 😂, but I hope this optimeize can help us to find the cause of the problem quickly when plugins conflict.

**Comment by lujiajing1126** [comment]
> @lujiajing1126 You are right, it can't resolve that problem and don't have much to do with each other 😂, but I hope this optimeize can help us to find the cause of the problem quickly when plugins conflict.

I agree this PR is a kind of optimization. But the changes here are totally irrelevant to the so-called "plugins conflict".

BootService is an internal service. Normally plugin developers and users do not implement their own BootServices.

**Pull request closed without merging**
