### PR TITLE
feature: gateway-plugin record request send exception

### PR DESCRIPTION
**Pull request by wangkang007**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please update changes.md in the root.

**Comment by wu-sheng** [comment]
@wangkang007 Are you still going to work on this?

**Comment by wangkang007** [comment]
sorry ！I'm busy these days. I'll update it as soon as possible

**Comment by wangkang007** [comment]
I see that error log reporting is added in version 8.8.0. Please help close pull request
@wu-sheng

**Pull request closed without merging**
