### PR TITLE
Support tracking the message listener of spring jms

### PR DESCRIPTION
**Pull request by hyhyf**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please follow plugin test doc to add test scenarios.

https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/plugin-test/

**Comment by hyhyf** [comment]
> Please follow plugin test doc to add test scenarios.
> 
> https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/plugin-test/

I cannot run testcase on local, what's wrong with docker?

**Comment by hyhyf** [comment]
+ java -jar -Xmx256m -Xms256m -Dconfigure.file=/d/project/skywalking-java/test/plugin/scenarios/spring-jms-5.x-scenario/configuration.yml -Dscenario.home=/d/project/skywalking-java/test/plugin/workspace/spring-jms-5.x-scenario/5.3.37 -Dscenario.name=spring-jms-5.x-scenario -Dscenario.version=5.3.37 -Doutput.dir=/d/project/skywalking-java/test/plugin/workspace/spring-jms-5.x-scenario/5.3.37 -Dagent.dir=/d/project/skywalking-java/test/plugin/../../skywalking-agent -Djacoco.home=/d/project/skywalking-java/test/plugin/../jacoco -Ddebug.mode= -Ddocker.image.version=1.0.0 /d/project/skywalking-java/test/plugin/dist/plugin-runner-helper.jar
+ [[ 0 -ne 0 ]]
+ echo 'start container of testcase.name=spring-jms-5.x-scenario-5.3.37'
start container of testcase.name=spring-jms-5.x-scenario-5.3.37
+ bash /d/project/skywalking-java/test/plugin/workspace/spring-jms-5.x-scenario/5.3.37/scenario.sh
time="2024-07-18T19:58:56+08:00" level=warning msg="D:\\project\\skywalking-java\\test\\plugin\\workspace\\spring-jms-5.x-scenario\\5.3.37\\docker-compose.yml: `version` is obsolete"
 spring-jms-5.x-scenario-5.3.37-1.0.0 Pulling
 activemq-server Pulling
 cc1a78bfd46b Pulling fs layer
 6861473222a6 Pulling fs layer
 7e0b9c3b5ae0 Pulling fs layer
 ae14ee39877a Pulling fs layer
 8085c1b536f0 Pulling fs layer
 6e1431e84c0c Pulling fs layer
 ca0e3df5a1fd Pulling fs layer
 d2cb611ced6c Pulling fs layer
 443cdb924ad0 Pulling fs layer
 ca0e3df5a1fd Waiting
 ae14ee39877a Waiting
 8085c1b536f0 Waiting
 6e1431e84c0c Waiting
 443cdb924ad0 Waiting
 d2cb611ced6c Waiting
 spring-jms-5.x-scenario-5.3.37-1.0.0 Error pull access denied for skywalking/agent-test-jvm, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error response from daemon: pull access denied for skywalking/agent-test-jvm, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
docker startup failure!

**Comment by hyhyf** [comment]
docker-compose.yml
----------------------------------------
version: '2.1'

networks:
   default:
     name: spring-jms-5.x-scenario-1.0.0

services:
    spring-jms-5.x-scenario-5.3.37-1.0.0:
        image: skywalking/agent-test-jvm:1.0.0
        links:
            - activemq-server
        environment:
            - activemq.server=tcp://activemq-server:61616
            - SCENARIO_START_SCRIPT=./bin/startup.sh
            - SCENARIO_NAME=spring-jms-5.x-scenario
            - SCENARIO_VERSION=5.3.37
            - SCENARIO_ENTRY_SERVICE=http://localhost:8080/spring-jms-5.x-scenario/case/spring-jms-scenario
            - SCENARIO_HEALTH_CHECK_URL=http://localhost:8080/spring-jms-5.x-scenario/case/healthCheck
            - SCENARIO_EXTEND_ENTRY_HEADER=
            - DEBUG_MODE=
        volumes:
            - D:/project/skywalking-java/test/plugin/../../skywalking-agent:/usr/local/skywalking/scenario/agent
            - D:/project/skywalking-java/test/plugin/workspace/spring-jms-5.x-scenario/5.3.37:/usr/local/skywalking/scenario
            - D:/project/skywalking-java/test/plugin/../jacoco:/jacoco
    activemq-server:
        image: rmohr/activemq:5.14.5
        hostname: activemq-server
        expose:
            - 8161
            - 61616

**Comment by wu-sheng** [comment]
You seems not to read logs?

docker login': denied: requested access to the resource is denied

**Comment by wu-sheng** [comment]
Login to dockerhub.

**Pull request closed without merging**
