### PR TITLE
Fix oracle lower case tns url parse error. (#11399)

### PR DESCRIPTION
**Pull request by Builder34**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes [[Bug] oracle lower case tns url parse err: skywalking#11399](https://github.com/apache/skywalking/issues/11399)
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

- To compatible upper and lower case Oracle TNS url parse.

### CODE REVIEW

**Comment by wu-sheng** [comment]
You should update the changes file. You clicked the box in the PR, but didn't actually do.

**Comment by Builder34** [comment]
https://www.caucho.com/resin-4.0/  dead Link check failed，do i need fix it ?

**Comment by wu-sheng** [comment]
Is the website changed? Or it is just down?

**Comment by Builder34** [comment]
I am not sure; it cannot be accessed, and no new accessible address was found.

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
The whole https://www.caucho.com is down. I am not sure. Merged your PR. It should not be your concern.

Thanks for your contribution.

**Pull request merged**
