### PR TITLE
[feat][pulsar] Support apache-pulsar functions.

### PR DESCRIPTION
**Pull request by dao-jun**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
 Mirror issue: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8996
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by dao-jun** [comment]
This PR is currently being drafted

**Comment by wu-sheng** [comment]
Could you explain what is Pulsar Function?

**Comment by dao-jun** [comment]
> Could you explain what is Pulsar Function?

Pulsar function is a sub-process forked by pulsar-broker, it provides a light-weight ETL framework for streaming process.
Users could extract data from datasources by using `Source`, process them by using `Function` and write the result to other datasources by using `Sink`.
For more context, please see: https://pulsar.apache.org/docs/3.1.x/functions-overview/

**Comment by wu-sheng** [comment]
> Mirror issue: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8996

One more question, why OTEL issue is linked here? Anything relative?

**Comment by wu-sheng** [comment]
> > Could you explain what is Pulsar Function?
> 
> Pulsar function is a sub-process forked by pulsar-broker, it provides a light-weight ETL framework for streaming process. Users could extract data from datasources by using `Source`, process them by using `Function` and write the result to other datasources by using `Sink`. For more context, please see: https://pulsar.apache.org/docs/3.1.x/functions-overview/

So, it means, the Function is created in the runtime? How would it be agent installed?

**Comment by dao-jun** [comment]
> > Mirror issue: [open-telemetry/opentelemetry-java-instrumentation#8996](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8996)
> 
> One more question, why OTEL issue is linked here? Anything relative?

Although the link is related to OTEL issue, but it pointed to the same question: the trace context will broken in Pulsar Function.

**Comment by dao-jun** [comment]
> > > Could you explain what is Pulsar Function?
> > 
> > 
> > Pulsar function is a sub-process forked by pulsar-broker, it provides a light-weight ETL framework for streaming process. Users could extract data from datasources by using `Source`, process them by using `Function` and write the result to other datasources by using `Sink`. For more context, please see: https://pulsar.apache.org/docs/3.1.x/functions-overview/
> 
> So, it means, the Function is created in the runtime? How would it be agent installed?

Function is a sub-process, pulsar-broker create the process by cmd commands. The javaagent would not mounted on pulsar-broker, but only pulsar-function process.

**Comment by wu-sheng** [comment]
I see. This looks a little strange. But anyway, its Pulsar's way.

From SkyWalking perspective, we would need you to build the test scenarios to verify the agent could attach to the created Function process as expected, and tracing could continue from Client->Pulsar->Function(agent installed).

**Comment by dao-jun** [comment]
> I see. This looks a little strange. But anyway, its Pulsar's way.

Yes, in the first I also think it looks a little strange, because the function process is a sub-process created by pulsar-broker. Mount javaagent on pulsar-function is an un-conventional usage, different with mount javaagent on user application. 

For the tests, I don't have a clue yet how to write it.  I‘ll study for a period of time first

**Comment by wu-sheng** [comment]
The test doc was linked from step <5> of https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/java-plugin-development-guide/#contribute-plugins-to-the-apache-skywalking-repository

And there are many existing cases there, but we don't even have this kind of dynamic mounting.

**Comment by wu-sheng** [comment]
> > > Mirror issue: [open-telemetry/opentelemetry-java-instrumentation#8996](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8996)
> > 
> > 
> > One more question, why OTEL issue is linked here? Anything relative?
> 
> Although the link is related to OTEL issue, but it pointed to the same question: the trace context will broken in Pulsar Function.

OK. I see. As it says `Mirror issue`. I am not familiar with that term.

**Comment by wu-sheng** [comment]
This has been opened for a week. Is there any plan still on this?

**Comment by wu-sheng** [comment]
Close for no update.

**Pull request closed without merging**
