### PR TITLE
fix ClassCircularityError

### PR DESCRIPTION
**Pull request by lujiajing1126**
We are also suffering from this issue. But it is not possible to reproduce it.

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #12572.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by lujiajing1126** [comment]
Since the discussion has not been updated for days. I would like to cherry-pick the commit from dd-trace-java.

The only issue for me is how to verify?

**Comment by wu-sheng** [comment]
Please revert the unexpected changes.

**Comment by wu-sheng** [comment]
> The only issue for me is how to verify?

There isn't an easy way to reproduce. Only in the environment it happened and waited.

**Comment by lujiajing1126** [comment]
> Please revert the unexpected changes.

Fixed

**Comment by wu-sheng** [comment]
Please recheck CI, or rerun? Others, I am good.

**Comment by lujiajing1126** [comment]
#718 preferred

**Pull request closed without merging**
