### PR TITLE
Optimize to final type

### PR DESCRIPTION
**Pull request by ruqinhu**
Optimize to final type

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why do you propose this change?

**Comment by ruqinhu** [comment]
> Why do you propose this change?

Minimize mutability: When a variable is declared as final, its value cannot be changed once it has been initialized. This is useful for declaring constants or other values that should not be modified.

**Comment by wu-sheng** [comment]
In theory, it is. But usually, the compiler and JIT would do that automatically, as they detected no one is going to change that, it is safe to cache during process.

And the codes you changed seem to be not called in high frequency.

**Comment by ruqinhu** [comment]
> In theory, it is. But usually, the compiler and JIT would do that automatically, as they detected no one is going to change that, it is safe to cache during process.
> 
> And the codes you changed seem to be not called in high frequency.

Okay, then I'll turn it of

**Comment by ruqinhu** [comment]
> In theory, it is. But usually, the compiler and JIT would do that automatically, as they detected no one is going to change that, it is safe to cache during process.
> 
> And the codes you changed seem to be not called in high frequency.

org.apache.skywalking.apm.agent.core.plugin.loader.InterceptorInstanceLoader#load seem to  called in high frequency.

Remove not used check, because Class.forName not find class, will throw ClassNotFoundException instead of null.

**Comment by wu-sheng** [comment]
Why ClassNotFound is a high frequency thing?

**Comment by ruqinhu** [comment]
> Why ClassNotFound is a high frequency thing?

It is unnecessary to judge whether it is empty. Will JIT also optimize it?

**Comment by wu-sheng** [comment]
I am not following. Instrument process only happens on booting and/or class first loaded.Nothing more.
Do you have any evidence to prove the performance has been impacted?

**Comment by ruqinhu** [comment]
> I am not following. Instrument process only happens on booting and/or class first loaded.Nothing more. Do you have any evidence to prove the performance has been impacted?

i see,

**Comment by wu-sheng** [comment]
We are happy to accept change if this thing really impacts perf.

**Pull request closed without merging**
