### PR TITLE
Basic testing support on arm64/v8 platforms

### PR DESCRIPTION
**Pull request by lujiajing1126**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

This PR is based on the work of #322 

 - [x] Migrate testing containers to `eclipse-termuin` images
 - [x] Update `maven-docker-plugin`

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you share steps to verify locally? I didn't use this part locally for a while
.

**Comment by lujiajing1126** [comment]
> Could you share steps to verify locally? I didn't use this part locally for a while .

1. First build SW Agent,
2. Run, for example, `bash ./test/plugin/run.sh -f spring-4.3.x-scenario` with `-f` to force building test containers

**Comment by wu-sheng** [comment]
```
[INFO] Packaging webapp
[INFO] Assembling webapp [spring-4.3.x-scenario] in [/Users/wusheng/github/skywalking-java/test/plugin/scenarios/spring-4.3.x-scenario/target/spring-4.3.x-scenario]
[INFO] Processing war project
[INFO] Copying webapp resources [/Users/wusheng/github/skywalking-java/test/plugin/scenarios/spring-4.3.x-scenario/src/main/webapp]
[INFO] Webapp assembled in [55 msecs]
[INFO] Building war: /Users/wusheng/github/skywalking-java/test/plugin/scenarios/spring-4.3.x-scenario/target/spring-4.3.x-scenario.war
[INFO] WEB-INF/web.xml already added, skipping
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.221 s
[INFO] Finished at: 2022-11-08T09:10:53+08:00
[INFO] ------------------------------------------------------------------------
+ mv ./target/spring-4.3.x-scenario.war /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE
+ java -jar -Xmx256m -Xms256m -Dconfigure.file=/Users/wusheng/github/skywalking-java/test/plugin/scenarios/spring-4.3.x-scenario/configuration.yml -Dscenario.home=/Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE -Dscenario.name=spring-4.3.x-scenario -Dscenario.version=4.3.24.RELEASE -Doutput.dir=/Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE -Dagent.dir=/Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/agent_with_optional -Djacoco.home=/Users/wusheng/github/skywalking-java/test/plugin/../jacoco -Ddebug.mode= -Ddocker.image.version=1.0.0 /Users/wusheng/github/skywalking-java/test/plugin/dist/plugin-runner-helper.jar
+ [[ 0 -ne 0 ]]
+ echo 'start container of testcase.name=spring-4.3.x-scenario-4.3.24.RELEASE'
start container of testcase.name=spring-4.3.x-scenario-4.3.24.RELEASE
+ bash /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE/scenario.sh
/Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE/scenario.sh: line 56: /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE/logs/container.log: No such file or directory
+ status=0
+ [[ 0 == 0 ]]
+ [[ -z '' ]]
+ rm -rf /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE
rm: /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE/agent: Permission denied
rm: /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE: Permission denied
```

I can build the images successfully, but this `Permission denied` makes me failed in testing.

**Review by wu-sheng — APPROVED** [review]

**Comment by lujiajing1126** [comment]
> ```
> [INFO] Packaging webapp
> [INFO] Assembling webapp [spring-4.3.x-scenario] in [/Users/wusheng/github/skywalking-java/test/plugin/scenarios/spring-4.3.x-scenario/target/spring-4.3.x-scenario]
> [INFO] Processing war project
> [INFO] Copying webapp resources [/Users/wusheng/github/skywalking-java/test/plugin/scenarios/spring-4.3.x-scenario/src/main/webapp]
> [INFO] Webapp assembled in [55 msecs]
> [INFO] Building war: /Users/wusheng/github/skywalking-java/test/plugin/scenarios/spring-4.3.x-scenario/target/spring-4.3.x-scenario.war
> [INFO] WEB-INF/web.xml already added, skipping
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  1.221 s
> [INFO] Finished at: 2022-11-08T09:10:53+08:00
> [INFO] ------------------------------------------------------------------------
> + mv ./target/spring-4.3.x-scenario.war /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE
> + java -jar -Xmx256m -Xms256m -Dconfigure.file=/Users/wusheng/github/skywalking-java/test/plugin/scenarios/spring-4.3.x-scenario/configuration.yml -Dscenario.home=/Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE -Dscenario.name=spring-4.3.x-scenario -Dscenario.version=4.3.24.RELEASE -Doutput.dir=/Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE -Dagent.dir=/Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/agent_with_optional -Djacoco.home=/Users/wusheng/github/skywalking-java/test/plugin/../jacoco -Ddebug.mode= -Ddocker.image.version=1.0.0 /Users/wusheng/github/skywalking-java/test/plugin/dist/plugin-runner-helper.jar
> + [[ 0 -ne 0 ]]
> + echo 'start container of testcase.name=spring-4.3.x-scenario-4.3.24.RELEASE'
> start container of testcase.name=spring-4.3.x-scenario-4.3.24.RELEASE
> + bash /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE/scenario.sh
> /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE/scenario.sh: line 56: /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE/logs/container.log: No such file or directory
> + status=0
> + [[ 0 == 0 ]]
> + [[ -z '' ]]
> + rm -rf /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE
> rm: /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE/agent: Permission denied
> rm: /Users/wusheng/github/skywalking-java/test/plugin/workspace/spring-4.3.x-scenario/4.3.24.RELEASE: Permission denied
> ```
> 
> I can build the images successfully, but this `Permission denied` makes me failed in testing.

Just a comment for the solution of this issue: 

We can use [`chmod -a`](https://www.unix.com/man-page/osx/1/chmod/) to match and remove `${whoami} deny write` [ACL entry](https://docker-docs.netlify.app/docker-for-mac/osxfs/#ownership).

**Pull request merged**
