### PR TITLE
Move armeria's plugins to apm-armeria-plugins

### PR DESCRIPTION
**Pull request by zhangrm**
…ia-plugins

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes [#10278.](https://github.com/apache/skywalking/issues/10278.)
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by zhangrm** [comment]
This pr is used to optimize the module structure of armeria

**Review by wu-sheng — APPROVED** [review]
Once all plugin tests are passed, this should be good.

**Comment by wu-sheng** [comment]
This will close https://github.com/apache/skywalking/issues/10278

**Comment by zhangrm** [comment]
> This will close [apache/skywalking#10278](https://github.com/apache/skywalking/issues/10278)

Glad to finish my first issue

**Pull request merged**
