### PR TITLE
[typo fix] fix milestone link

### PR DESCRIPTION
**Pull request by cyberdak**
fix changs.md .
No any code changes.

### CODE REVIEW

**Comment by cyberdak** [comment]
@wu-sheng review please

**Comment by wu-sheng** [comment]
The old one is wrong, but yours is wrong too. Milestone is managed in the main repository.

**Comment by cyberdak** [comment]
There is also a "Java 8.9.0" milestone in the main repository , but this repository's milestone links to 39 prs , the main milestone only links to 19 prs which loss some.
If doc link to the main milestone , we should fix the main milestone.

this repo's milestone : https://github.com/apache/skywalking-java/milestone/2?closed=1
the main repo's milestone : https://github.com/apache/skywalking/milestone/108?closed=1

**Comment by wu-sheng** [comment]
That is not how it works. In SkyWalking, issue's milestone(main repo's) is the only place to track planned things. This repo's milestone is for cataloging the PR. In the release tag, you have already known which merged PRs are included. There is not much point to link them again.
On the other hand, some proposals may be discussed, even rejected(so no PR), in the main issue tracker. This is why we link to it from here.

**Pull request closed without merging**
