### PR TITLE
Rename`JDBI` to `JDBC`

### PR DESCRIPTION
**Pull request by nisiyong**
Many spans named `JDBI` are confusing and I think we should correct that typo.

- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-java/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
This is a legacy thing, rather than a typo.
We were following Open Tracing tag, which declare this. I think it is fine to correct them, but you need to make sure all tests passed

**Comment by nisiyong** [comment]
> This is a legacy thing, rather than a typo.

Thanks for your mention, and I have found that [JDBI](https://jdbi.org/) meaning. `JDBC` still will be easier to understand. All tests are passed, please take a look.

**Comment by wu-sheng** [comment]
Oracle case is still failing.

**Comment by nisiyong** [comment]
I checked the test case failed message, and I think this error is not related to this PR. Could you rerun the `oracle-scenario`?
image

**Comment by wu-sheng** [comment]
I had re-runed twice. It keeps failure.

**Comment by nisiyong** [comment]
I think I should create a PR at repo [SkyAPM/java-plugin-extensions](https://github.com/SkyAPM/java-plugin-extensions) first because the oracle plugin is out of the official repo.

**Comment by wu-sheng** [comment]
A new release of the Oracle plugin repo

https://github.com/SkyAPM/java-plugin-extensions/releases/tag/2.3.0

**Comment by nisiyong** [comment]
The `oracle-scenario` test case runs successfully now.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
